"""Initial migration

Revision ID: 9513acd42747
Revises:
Create Date: 2025-02-09 02:54:48.803960

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9513acd42747"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pastes",
        sa.Column("pasteID", sa.String(length=4), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("extension", sa.String(length=50), nullable=True),
        sa.Column("s3_link", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expiresat", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("pasteID"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pastes")
    # ### end Alembic commands ###
